# Goal: Learn Pandas step by step using real datasets created with NumPy
#### Common Setup (Run Once)

In [2]:
import numpy as np
import pandas as pd

## DATASET 1: Titanic-Like Passenger Dataset
### Purpose: Learn data inspection, filtering, missing values, grouping

#### Create Dataset using NumPy
---

In [3]:
np.random.seed(1)
rows = 200

In [4]:
df = pd.DataFrame({
    "PassengerId": np.arange(1, rows + 1),
    "Name": np.random.choice(["Mr. John", "Mrs. Anna", "Miss Emma", "Dr. Smith"], rows),
    "Age": np.random.choice(np.append(np.random.randint(1, 80, 180), [np.nan]*20), rows),
    "Sex": np.random.choice(["male", "female"], rows),
    "Pclass": np.random.choice([1, 2, 3], rows),
    "Fare": np.round(np.random.uniform(10, 500, rows), 2)
})

#### View Data
----

In [5]:
df.head() # View first 5 rows

   PassengerId       Name   Age     Sex  Pclass    Fare
0            1  Mrs. Anna  40.0    male       2  461.14
1            2  Dr. Smith   NaN    male       1  333.43
2            3   Mr. John  75.0    male       1  348.14
3            4   Mr. John  63.0  female       2   92.36
4            5  Dr. Smith  39.0  female       1  346.02

In [6]:
df.tail() # View last 5 rows

     PassengerId       Name   Age     Sex  Pclass    Fare
195          196  Miss Emma  40.0    male       2  136.23
196          197  Dr. Smith  33.0  female       1  300.03
197          198  Mrs. Anna  75.0    male       3   53.22
198          199  Mrs. Anna   NaN    male       2  431.91
199          200  Miss Emma  33.0    male       3   45.51

In [7]:
df.sample(3) # View random 3 rows

     PassengerId       Name   Age     Sex  Pclass    Fare
128          129   Mr. John  18.0    male       3  338.25
175          176   Mr. John  33.0  female       3  329.26
41            42  Mrs. Anna  36.0    male       1   47.32

#### Inspect Structure
----

In [8]:
df.shape # Number of rows and columns

(200, 6)

In [9]:
df.columns # Column names

Index(['PassengerId', 'Name', 'Age', 'Sex', 'Pclass', 'Fare'], dtype='str')

In [10]:
df.info() # Data types and missing values

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Name         200 non-null    str
 2   Age          182 non-null    float64
 3   Sex          200 non-null    str
 4   Pclass       200 non-null    int64
 5   Fare         200 non-null    float64
dtypes: float64(2), int64(2), str(2)
memory usage: 9.5 KB

In [11]:
df.describe() # Statistical summary

       PassengerId         Age      Pclass        Fare
count   200.000000  182.000000  200.000000  200.000000
mean    100.500000   43.318681    2.035000  251.249700
std      57.879185   22.078153    0.804369  146.847353
min       1.000000    1.000000    1.000000   11.250000
25%      50.750000   25.250000    1.000000  115.550000
50%     100.500000   41.000000    2.000000  265.430000
75%     150.250000   63.000000    3.000000  371.432500
max     200.000000   79.000000    3.000000  493.680000

#### Handle Missing Data
---

In [12]:
df.isnull().sum() # Count missing values

PassengerId     0
Name            0
Age            18
Sex             0
Pclass          0
Fare            0
dtype: int64

In [13]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

#### Filtering Rows
---

In [14]:
df[df["Age"]>30]

     PassengerId       Name        Age     Sex  Pclass    Fare
0              1  Mrs. Anna  40.000000    male       2  461.14
1              2  Dr. Smith  43.318681    male       1  333.43
2              3   Mr. John  75.000000    male       1  348.14
3              4   Mr. John  63.000000  female       2   92.36
4              5  Dr. Smith  39.000000  female       1  346.02
..           ...        ...        ...     ...     ...     ...
195          196  Miss Emma  40.000000    male       2  136.23
196          197  Dr. Smith  33.000000  female       1  300.03
197          198  Mrs. Anna  75.000000    male       3   53.22
198          199  Mrs. Anna  43.318681    male       2  431.91
199          200  Miss Emma  33.000000    male       3   45.51

[140 rows x 6 columns]

In [15]:
df[df["Sex"] == "female"]

     PassengerId       Name        Age     Sex  Pclass    Fare
3              4   Mr. John  63.000000  female       2   92.36
4              5  Dr. Smith  39.000000  female       1  346.02
5              6  Mrs. Anna  26.000000  female       2  304.88
8              9  Dr. Smith  29.000000  female       3   44.05
10            11   Mr. John  77.000000  female       3  247.52
..           ...        ...        ...     ...     ...     ...
186          187   Mr. John  43.318681  female       1  148.20
190          191  Miss Emma  68.000000  female       1  367.68
191          192  Miss Emma  78.000000  female       3   12.94
193          194  Dr. Smith  43.318681  female       1   25.29
196          197  Dr. Smith  33.000000  female       1  300.03

[99 rows x 6 columns]

#### Grouping & Aggregation
----

In [16]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    237.222623
2    281.545775
3    232.200147
Name: Fare, dtype: float64

----
----
## DATASET 2: Student Performance Dataset
### Purpose: Sorting, value counts, apply, conditional columns

#### Create Dataset
---

In [17]:
np.random.seed(2)
rows=150

In [18]:
df=pd.DataFrame({
    "StudentId" : np.arange(1,rows+1),
    "Age" : np.random.randint(18,30,rows),
    "Gender" : np.random.choice(["male","female"],rows),
    "Course" : np.random.choice(["AI", "DS", "ML", "Python"],rows),
    "Marks" : np.random.randint(35,100,rows)    
})

#### Sorting Data
---

In [19]:
df.sort_values(by="Marks",ascending=False)

     StudentId  Age  Gender  Course  Marks
140        141   26  female      DS     99
47          48   26  female      DS     99
30          31   26  female      ML     99
145        146   25  female      ML     99
19          20   22  female  Python     98
..         ...  ...     ...     ...    ...
110        111   29  female      ML     38
144        145   18  female  Python     37
40          41   28  female      ML     37
14          15   22  female      ML     35
11          12   23  female      ML     35

[150 rows x 5 columns]

#### Value Counts
---

In [20]:
df["Gender"].value_counts()

Gender
female    84
male      66
Name: count, dtype: int64

#### Apply Function
---

In [21]:
df["Result"]=df["Marks"].apply(lambda x: "Pass" if x>=50 else "Fail")
df

     StudentId  Age  Gender Course  Marks Result
0            1   26    male     AI     65   Pass
1            2   26  female     DS     41   Fail
2            3   24    male     DS     56   Pass
3            4   29  female     ML     52   Pass
4            5   20  female     AI     72   Pass
..         ...  ...     ...    ...    ...    ...
145        146   25  female     ML     99   Pass
146        147   18  female     DS     64   Pass
147        148   23  female     AI     68   Pass
148        149   29    male     ML     83   Pass
149        150   28  female     DS     87   Pass

[150 rows x 6 columns]

#### Grouping
----

In [22]:
df.groupby("Course")["Marks"].mean()

Course
AI        68.185185
DS        64.611111
ML        62.125000
Python    68.282051
Name: Marks, dtype: float64

---
____
## DATASET 3: Employee Dataset
### Purpose: Rename, drop, mapping, aggregation

#### Create Dataset
-----

In [23]:
np.random.seed(3)
rows = 120

In [29]:
df = pd.DataFrame({
    "EmpId": np.arange(1, rows + 1),
    "Dept": np.random.choice(["HR", "IT", "Sales"], rows),
    "Salary": np.random.randint(30000, 150000, rows),
    "Gender": np.random.choice(["male", "female"], rows)
})

#### Rename & Drop
---

In [30]:
df.rename(columns={"Dept": "Department"}, inplace=True)
df

     EmpId Department  Salary  Gender
0        1         HR   42529    male
1        2         IT   90053  female
2        3         IT   99425    male
3        4      Sales  107704  female
4        5      Sales   32329    male
..     ...        ...     ...     ...
115    116      Sales  117576    male
116    117         IT   88503    male
117    118         HR   62174    male
118    119      Sales   91217  female
119    120      Sales  116585  female

[120 rows x 4 columns]

In [31]:
df.drop("Gender", axis=1, inplace=True)
df

     EmpId Department  Salary
0        1         HR   42529
1        2         IT   90053
2        3         IT   99425
3        4      Sales  107704
4        5      Sales   32329
..     ...        ...     ...
115    116      Sales  117576
116    117         IT   88503
117    118         HR   62174
118    119      Sales   91217
119    120      Sales  116585

[120 rows x 3 columns]

#### Aggregation
---

In [32]:
df.groupby("Department")["Salary"].agg(["mean", "max"])

                     mean     max
Department
HR           90146.578947  147389
IT           91684.500000  142926
Sales       101017.062500  148530